version: '3'
services:
  ui:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443/tcp
    volumes:
     - ./dist/apps/ui:/usr/share/nginx/html/
     - ./default.conf/:/etc/nginx/conf.d/default.conf
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
    networks:
     - app-network

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot


networks:
  app-network:
    driver: bridge