const supportedLanguages = [
    'abap',
    'apex',
    'azcli',
    'bat',
    'bicep',
    'cameligo',
    'clojure',
    'coffee',
    'cpp',
    'csharp',
    'csp',
    'css',
    'cypher',
    'dart',
    'dockerfile',
    'ecl',
    'elixir',
    'flow9',
    'freemarker2',
    'fsharp',
    'go',
    'graphql',
    'handlebars',
    'hcl',
    'html',
    'ini',
    'java',
    'javascript',
    'json',
    'julia',
    'kotlin',
    'less',
    'lexon',
    'liquid',
    'lua',
    'm3',
    'markdown',
    'mips',
    'msdax',
    'mysql',
    'objective-c',
    'pascal',
    'pascaligo',
    'perl',
    'pgsql',
    'php',
    'pla',
    'postiats',
    'powerquery',
    'powershell',
    'protobuf',
    'pug',
    'python',
    'qsharp',
    'r',
    'razor',
    'redis',
    'redshift',
    'restructuredtext',
    'ruby',
    'rust',
    'sb',
    'scala',
    'scheme',
    'scss',
    'shell',
    'solidity',
    'sophia',
    'sparql',
    'sql',
    'st',
    'swift',
    'systemverilog',
    'tcl',
    'test',
    'twig',
    'typescript',
    'vb',
    'wgsl',
    'xml',
    'yaml',
] as const;

type LanguageType = (typeof supportedLanguages)[number];

export const languageTypeByExtensionMap: { [ext: string]: LanguageType } = {
    abap: 'abap',
    cls: 'apex',
    azcli: 'azcli',
    bat: 'bat',
    bicep: 'bicep',
    ml: 'cameligo',
    cljs: 'clojure',
    coffee: 'coffee',
    cpp: 'cpp',
    cs: 'csharp',
    css: 'css',
    cypher: 'cypher',
    dart: 'dart',
    dockerfile: 'dockerfile',
    ecl: 'ecl',
    ex: 'elixir',
    fm: 'freemarker2',
    fs: 'fsharp',
    go: 'go',
    gql: 'graphql',
    hbs: 'handlebars',
    hcl: 'hcl',
    html: 'html',
    ini: 'ini',
    java: 'java',
    js: 'javascript',
    json: 'json',
    jsx: 'javascript',
    jl: 'julia',
    kt: 'kotlin',
    less: 'less',
    lua: 'lua',
    md: 'markdown',
    mips: 'mips',
    sql: 'mysql',
    m: 'objective-c',
    pas: 'pascal',
    pl: 'perl',
    php: 'php',
    pq: 'powerquery',
    ps1: 'powershell',
    proto: 'protobuf',
    pug: 'pug',
    py: 'python',
    qs: 'qsharp',
    r: 'r',
    razor: 'razor',
    rb: 'ruby',
    rs: 'rust',
    scala: 'scala',
    scm: 'scheme',
    scss: 'scss',
    sh: 'shell',
    sol: 'solidity',
    sparql: 'sparql',
    swift: 'swift',
    sv: 'systemverilog',
    tcl: 'tcl',
    twig: 'twig',
    ts: 'typescript',
    tsx: 'typescript',
    vb: 'vb',
    xml: 'xml',
    yaml: 'yaml',
    yml: 'yaml',
};
